### ISSUE TITLE
[FEATURE] Allow "mfsymlinks" mount option

### ISSUE THREAD

**Issue by cheahkhing** [cloudfoundry/smbbroker#3] opened 2019-10-24 00:02 UTC
Hi,
I am currently facing an issue with CIFS volume doesn't work with symlinks when running in CF containers.

And, I found that having this option might be able to solve the issue.
Can this option be added as well?

**Comment by DennisDenuto** [comment] 2019-10-24 16:17
Hi @cheahkhing can you provide the steps to reproduce this issue and the error from the logs you are seeing?

**Comment by cheahkhing** [comment] 2019-10-25 13:48
Hi @DennisDenuto ,

The issue is quite straightforward:
1. Mount a CIFS volume in CF
2. Push an docker container app in CF
3. Let your container app to run a script or a command to create symlink to the mounted volume.

You'll get this error:
Cannot create symlink to '/var/lib/apps-content/': Operation not supported

**Comment by julian-hj** [comment] 2019-10-28 18:19
Hi @cheahkhing 

I am not able to reproduce the issue with the steps above.  I can create links to a mounted SMB volume from either a docker app, or a regular buildpack app.

Can you confirm whether you are trying to make links to the mounted volume, or you are trying to create a link within the mounted volume?  My understanding is that the `mfsymlinks` option would only help the latter case.

Thanks
-Julian

**Comment by cheahkhing** [comment] 2019-10-28 23:52
That's right @julian-hj , my case is the latter one. The error should appear when you're trying to create symlinks within the mounted volume.

**Comment by julian-hj** [comment] 2019-10-29 17:44
Hi @cheahkhing,
OK, we are able to reproduce your issue, and it does appear that with our smb test server, the `mfsymlink` mount option resolves the issue.

I am interested to understand more about your use case however.  What problem are you trying to solve with symlinks? And are the symlinks you are creating confined to relative links between files in the same share, or do they link out files or folders elsewhere in the container?

**Comment by cheahkhing** [comment] 2019-10-30 01:23
Hi @julian-hj , it is quite common for apps in container to create symlinks regardless whether it is within smb mounts or local filesystem. 
My use case is quite simple as in i was using a nodejs CLI tools, where it will need to create symlinks between the files / directories in the shared.
Ofcoz it works fine if the directories are local fs, but the reason for the smb mounts are meant for the files /directories to be shared outside of containers.
So, i got no other ways currently to use that tools, nor to manually implement scripts to symlinks myself.
I am currently using rsync as a temporarily solution for my problem. :(

**Comment by julian-hj** [comment] 2020-01-27 20:02
This is addressed in [version 2.2.0 of smb-volume-release](https://github.com/cloudfoundry/smb-volume-release/releases/tag/v2.2.0).

**Closed by julian-hj** 2020-01-27 20:02 UTC
Labels: accepted
